#!/usr/bin/env python3
import json
from model_helper import load_feature_sets

SUBMODEL_1 = "../data/logistic-model.json"
SUBMODEL_2 = "../data/mlp-model.json"
SUBMODEL_3 = "../data/rnn-model.json"
Y_RANGE = 2 # 0 or 1


def is_prediction_correct(sample, y_count):
	"""
	Check if prediction generated by ensemble model is correct or not.
	"""
	prediction = False

	for i in range(Y_RANGE):
		prediction = prediction or (y_count[i] > y_count[1-i] and sample[i] == 1)

	return prediction


def load_submodels():
	"""
	Load the predictions generated after testing the individual models.
	"""
	submodels = []

	with open(SUBMODEL_1) as infile:
		submodels.append(json.load(infile))
	with open(SUBMODEL_2) as infile:
		submodels.append(json.load(infile))
	with open(SUBMODEL_3) as infile:
		submodels.append(json.load(infile))

	return submodels


def test():
	"""
	Test the accuracy.
	"""
	submodels = load_submodels()
	test_x, test_y = load_feature_sets(False)

	total_sample = len(test_y)
	correct_predictions = 0

	for i in range(0, total_sample):
		y_count = [0] * Y_RANGE

		for submodel in submodels:
			y_count[submodel[i]] += 1

		if is_prediction_correct(test_y[i], y_count):
			correct_predictions += 1

	print("Accuracy: ", correct_predictions/total_sample)


if __name__ == "__main__":
	test()